Repository ZephyrCloudIO/zephyr-packages, pull requests merged in 2025-05, with the labels that each got.

#105 fix: provenance for canary release workflow
  .github/workflows/on_canary_release.yml
Labels: bug

#119 feat: add vite runtime remote replacement (side panel support)
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  examples/vite-react-mf/host/package.json
  examples/vite-react-mf/host/src/App.tsx
  examples/vite-react-mf/host/vite.config.ts
  examples/vite-react-mf/remote/vite.config.ts
  examples/vite-react-mf/rspack/rspack.config.js
  libs/vite-plugin-zephyr/src/lib/internal/extract/extract_mf_plugin.ts
  libs/vite-plugin-zephyr/src/lib/internal/mf-vite-etl/extract-mf-vite-remotes.ts
  libs/vite-plugin-zephyr/src/lib/internal/mf-vite-etl/load_resolved_remotes.ts
  libs/vite-plugin-zephyr/src/lib/internal/mf-vite-etl/remote_map_parser.ts
  libs/vite-plugin-zephyr/src/lib/internal/mf-vite-etl/runtime_plugin.ts
  libs/vite-plugin-zephyr/src/lib/internal/mf-vite-etl/runtime_plugins_parser.ts
  libs/vite-plugin-zephyr/src/lib/vite-plugin-zephyr.ts
  libs/zephyr-agent/src/lib/transformers/ze-build-dash-data.ts
  libs/zephyr-agent/src/zephyr-engine/index.ts
  nx.json
Labels: enhancement

#125 feat: add support for new Nx Module Federation plugin system
  libs/zephyr-agent/src/lib/build-context/ze-util-get-git-info.ts
  libs/zephyr-xpack-internal/src/federation-dashboard-legacy/get-build-stats.ts
  libs/zephyr-xpack-internal/src/federation-dashboard-legacy/utils/federation-dashboard-plugin/FederationDashboardPlugin.ts
  libs/zephyr-xpack-internal/src/xpack-extract/extract-federated-dependency-pairs.ts
  libs/zephyr-xpack-internal/src/xpack-extract/extract-federation-config.ts
  libs/zephyr-xpack-internal/src/xpack-extract/index.ts
  libs/zephyr-xpack-internal/src/xpack-extract/iterate-federated-remote-config.ts
  libs/zephyr-xpack-internal/src/xpack-extract/mut-webpack-federated-remotes-config.ts
  libs/zephyr-xpack-internal/src/xpack.types.ts
Labels: enhancement

#126 fix: adding example on new nx mf plugin system
  examples/rspack-nx-mf/apps/host/.eslintrc.json
  examples/rspack-nx-mf/apps/host/jest.config.ts
  examples/rspack-nx-mf/apps/host/module-federation.config.ts
  examples/rspack-nx-mf/apps/host/package.json
  examples/rspack-nx-mf/apps/host/project.json
  examples/rspack-nx-mf/apps/host/rspack.config.prod.ts
  examples/rspack-nx-mf/apps/host/rspack.config.ts
  examples/rspack-nx-mf/apps/host/src/app/app.module.css
  examples/rspack-nx-mf/apps/host/src/app/app.spec.tsx
  examples/rspack-nx-mf/apps/host/src/app/app.tsx
  examples/rspack-nx-mf/apps/host/src/app/nx-welcome.tsx
  examples/rspack-nx-mf/apps/host/src/assets/.gitkeep
  examples/rspack-nx-mf/apps/host/src/bootstrap.tsx
  examples/rspack-nx-mf/apps/host/src/favicon.ico
  examples/rspack-nx-mf/apps/host/src/index.html
  examples/rspack-nx-mf/apps/host/src/main.ts
  examples/rspack-nx-mf/apps/host/src/remotes.d.ts
  examples/rspack-nx-mf/apps/host/src/styles.css
  examples/rspack-nx-mf/apps/host/tsconfig.app.json
  examples/rspack-nx-mf/apps/host/tsconfig.json
  examples/rspack-nx-mf/apps/host/tsconfig.spec.json
  examples/rspack-nx-mf/apps/remote/.eslintrc.json
  examples/rspack-nx-mf/apps/remote/jest.config.ts
  examples/rspack-nx-mf/apps/remote/module-federation.config.ts
  examples/rspack-nx-mf/apps/remote/package.json
  examples/rspack-nx-mf/apps/remote/project.json
  examples/rspack-nx-mf/apps/remote/rspack.config.prod.ts
  examples/rspack-nx-mf/apps/remote/rspack.config.ts
  examples/rspack-nx-mf/apps/remote/src/app/app.module.css
  examples/rspack-nx-mf/apps/remote/src/app/app.spec.tsx
  examples/rspack-nx-mf/apps/remote/src/app/app.tsx
  examples/rspack-nx-mf/apps/remote/src/app/nx-welcome.tsx
  examples/rspack-nx-mf/apps/remote/src/assets/.gitkeep
  examples/rspack-nx-mf/apps/remote/src/bootstrap.tsx
  examples/rspack-nx-mf/apps/remote/src/favicon.ico
  examples/rspack-nx-mf/apps/remote/src/index.html
  examples/rspack-nx-mf/apps/remote/src/main.ts
  examples/rspack-nx-mf/apps/remote/src/remote-entry.ts
  examples/rspack-nx-mf/apps/remote/src/styles.css
  examples/rspack-nx-mf/apps/remote/tsconfig.app.json
  examples/rspack-nx-mf/apps/remote/tsconfig.json
  examples/rspack-nx-mf/apps/remote/tsconfig.spec.json
  examples/rspack-nx-mf/package.json
  libs/zephyr-xpack-internal/src/federation-dashboard-legacy/get-build-stats.ts
  nx.json
  package.json
  pnpm-lock.yaml
Labels: enhancement

#74 Feat: add basehref
  .gitignore
  examples/rspress-ssg/doc_build/404.html
  examples/rspress-ssg/doc_build/guide/index.html
  examples/rspress-ssg/doc_build/hello.html
  examples/rspress-ssg/doc_build/index.html
  examples/rspress-ssg/doc_build/rspress-dark-logo.png
  examples/rspress-ssg/doc_build/rspress-icon.png
  examples/rspress-ssg/doc_build/rspress-light-logo.png
  examples/rspress-ssg/doc_build/static/css/styles.e45a8283.css
  examples/rspress-ssg/doc_build/static/js/774.bae6c82e.js
  examples/rspress-ssg/doc_build/static/js/774.bae6c82e.js.LICENSE.txt
  examples/rspress-ssg/doc_build/static/js/async/465.1b2a5779.js
  examples/rspress-ssg/doc_build/static/js/async/747.ff82c490.js
  examples/rspress-ssg/doc_build/static/js/async/853.f45c9585.js
  examples/rspress-ssg/doc_build/static/js/index.7adb548c.js
  examples/rspress-ssg/doc_build/static/js/lib-react.7475082a.js
  examples/rspress-ssg/doc_build/static/js/lib-react.7475082a.js.LICENSE.txt
  examples/rspress-ssg/doc_build/static/js/lib-router.ebc9556e.js
  examples/rspress-ssg/doc_build/static/js/lib-router.ebc9556e.js.LICENSE.txt
  examples/rspress-ssg/doc_build/static/js/styles.8cffb023.js
  examples/rspress-ssg/doc_build/static/search_index.c22ed586.json
  examples/rspress-ssg/plugin.ts
  libs/vite-plugin-zephyr/src/lib/vite-plugin-zephyr.ts
  libs/zephyr-agent/src/index.ts
  libs/zephyr-agent/src/lib/transformers/__test__/ze-basehref-handler.spec.ts
  libs/zephyr-agent/src/lib/transformers/ze-basehref-handler.ts
  libs/zephyr-agent/src/lib/transformers/ze-build-snapshot.ts
  libs/zephyr-agent/src/zephyr-engine/index.ts
  libs/zephyr-rolldown-plugin/src/lib/zephyr-rolldown-plugin.ts
  libs/zephyr-rsbuild-plugin/.eslintrc.json
  libs/zephyr-rsbuild-plugin/.npmignore
  libs/zephyr-rsbuild-plugin/jest.config.ts
  libs/zephyr-rsbuild-plugin/package.json
  libs/zephyr-rsbuild-plugin/project.json
  libs/zephyr-rsbuild-plugin/src/index.ts
  libs/zephyr-rsbuild-plugin/src/rsbuild-plugin/with-zephyr.ts
  libs/zephyr-rsbuild-plugin/src/rsbuild-plugin/ze-rsbuild-plugin.ts
  libs/zephyr-rsbuild-plugin/src/types/index.ts
  libs/zephyr-rsbuild-plugin/tsconfig.json
  libs/zephyr-rsbuild-plugin/tsconfig.lib.json
  libs/zephyr-rsbuild-plugin/tsconfig.spec.json
  libs/zephyr-rspack-plugin/src/rspack-plugin/ze-rspack-plugin.ts
  libs/zephyr-webpack-plugin/src/webpack-plugin/ze-webpack-plugin.ts
  libs/zephyr-xpack-internal/src/basehref/basehref-integration.ts
  libs/zephyr-xpack-internal/src/index.ts
  libs/zephyr-xpack-internal/src/xpack.types.ts
  pnpm-lock.yaml
Labels: enhancement, QA: Approved, Ready for testing

#142 fix: examples
  examples/parcel-react/package.json
  examples/react-micro-frontends/apps/team-blue/project.json
  examples/react-micro-frontends/apps/team-blue/src/assets/favicon.ico
  examples/react-micro-frontends/apps/team-blue/webpack.config.ts
  examples/react-micro-frontends/apps/team-green/src/assets/favicon.ico
  examples/react-micro-frontends/apps/team-green/webpack.config.ts
  examples/react-micro-frontends/apps/team-red/src/app/team-red-layout.tsx
  examples/react-micro-frontends/apps/team-red/src/assets/favicon.ico
  examples/react-micro-frontends/apps/team-red/src/favicon.ico
  examples/react-micro-frontends/apps/team-red/src/remotes.d.ts
  examples/react-micro-frontends/apps/team-red/tsconfig.json
  examples/react-micro-frontends/apps/team-red/webpack.config.ts
  examples/react-micro-frontends/package.json
  examples/rspack-mf/apps/host/module-federation.config.js
  examples/rspack-mf/apps/host/rspack.config.js
  examples/rspack-mf/apps/remote/module-federation.config.js
  examples/rspack-mf/apps/remote/rspack.config.js
  examples/rspack-nx-mf/apps/host/module-federation.config.ts
  examples/rspack-nx-mf/apps/host/src/index.html
  examples/rspack-nx-mf/apps/host/src/remotes.d.ts
  examples/rspack-nx-mf/apps/remote/module-federation.config.ts
  examples/rspack-nx-mf/apps/remote/src/index.html
  examples/vite-react-ts/package.json
  libs/create-zephyr-apps/src/templates.ts
  libs/vite-plugin-zephyr/src/lib/vite-plugin-zephyr.ts
  libs/zephyr-agent/src/lib/build-context/ze-util-get-git-info.ts
  libs/zephyr-xpack-internal/src/federation-dashboard-legacy/get-build-stats.ts
  libs/zephyr-xpack-internal/src/federation-dashboard-legacy/utils/federation-dashboard-plugin/FederationDashboardPlugin.ts
  libs/zephyr-xpack-internal/src/xpack-extract/mut-webpack-federated-remotes-config.ts
  package.json
  pnpm-lock.yaml
Labels: bug, QA: Approved
