Repository ZephyrCloudIO/zephyr-packages, pull requests merged in 2025-06, with the labels that each got.

#144 fix: add app uid to remotes on build stats
  libs/zephyr-xpack-internal/src/federation-dashboard-legacy/get-build-stats.ts
Labels: bug

#150 fix: parse as buffer instead of text decode
  libs/vite-plugin-zephyr/src/lib/internal/extract/__test__/extract_vite_assets_map.test.ts
  libs/vite-plugin-zephyr/src/lib/internal/extract/extract_vite_assets_map.ts
Labels: bug

#153 fix: adjusting remote resolution on samples
  examples/react-micro-frontends/apps/team-red/package.json
  examples/rspack-mf/apps/host/package.json
  examples/rspack-nx-mf/apps/host/package.json
  examples/vite-react-mf/host/package.json
  libs/zephyr-agent/src/lib/build-context/__test__/ze-util-parse-ze-dependencies.test.ts
  libs/zephyr-agent/src/lib/build-context/ze-util-parse-ze-dependencies.ts
Labels: bug

#148 feat: rsplugin and rspress example
  examples/rspack-sample-app/package.json
  examples/rspress-ssg/.gitignore
  examples/rspress-ssg/README.md
  examples/rspress-ssg/docs/_meta.json
  examples/rspress-ssg/docs/guide/_meta.json
  examples/rspress-ssg/docs/guide/index.md
  examples/rspress-ssg/docs/hello.md
  examples/rspress-ssg/docs/index.md
  examples/rspress-ssg/docs/public/rspress-dark-logo.png
  examples/rspress-ssg/docs/public/rspress-icon.png
  examples/rspress-ssg/docs/public/rspress-light-logo.png
  examples/rspress-ssg/package.json
  examples/rspress-ssg/rspress.config.ts
  examples/rspress-ssg/tsconfig.json
  libs/zephyr-modernjs-plugin/src/modernjs-plugin/with-zephyr.ts
  libs/zephyr-rspress-plugin/.eslintrc.json
  libs/zephyr-rspress-plugin/.npmignore
  libs/zephyr-rspress-plugin/LICENSE
  libs/zephyr-rspress-plugin/README.md
  libs/zephyr-rspress-plugin/jest.config.ts
  libs/zephyr-rspress-plugin/package.json
  libs/zephyr-rspress-plugin/project.json
  libs/zephyr-rspress-plugin/src/__test__/with-zephyr.spec.ts
  libs/zephyr-rspress-plugin/src/__test__/zephyrRsbuildPlugin.spec.ts
  libs/zephyr-rspress-plugin/src/__test__/zephyrRspressSSGPlugin.spec.ts
  libs/zephyr-rspress-plugin/src/index.ts
  libs/zephyr-rspress-plugin/src/internal/__test__/buildAsset.spec.ts
  libs/zephyr-rspress-plugin/src/internal/__test__/buildStats.spec.ts
  libs/zephyr-rspress-plugin/src/internal/__test__/setupZeDeploy.spec.ts
  libs/zephyr-rspress-plugin/src/internal/__test__/showFiles.spec.ts
  libs/zephyr-rspress-plugin/src/internal/__test__/walkFiles.spec.ts
  libs/zephyr-rspress-plugin/src/internal/assets/buildAssets.ts
  libs/zephyr-rspress-plugin/src/internal/assets/setupZeDeploy.ts
  libs/zephyr-rspress-plugin/src/internal/files/showFiles.ts
  libs/zephyr-rspress-plugin/src/internal/files/walkFiles.ts
  libs/zephyr-rspress-plugin/src/internal/stats/buildStats.ts
  libs/zephyr-rspress-plugin/src/types/index.ts
  libs/zephyr-rspress-plugin/src/with-zephyr.ts
  libs/zephyr-rspress-plugin/src/zephyrRsbuildPlugin.ts
  libs/zephyr-rspress-plugin/src/zephyrRspressSSGPlugin.ts
  libs/zephyr-rspress-plugin/tsconfig.json
  libs/zephyr-rspress-plugin/tsconfig.lib.json
  libs/zephyr-rspress-plugin/tsconfig.spec.json
  libs/zephyr-xpack-internal/src/xpack-extract/build-webpack-assets-map.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: enhancement

#165 chore: remove withZephyr options from docs
  libs/zephyr-rolldown-plugin/README.md
  libs/zephyr-rspack-plugin/README.md
  libs/zephyr-rspress-plugin/README.md
  libs/zephyr-webpack-plugin/README.md
Labels: documentation
