Repository ZephyrCloudIO/zephyr-packages, pull requests merged in 2025-03, with the labels that each got.

#51 feat: Authentication enhancement, adding prompt before opening browser and manual option
  libs/zephyr-agent/src/index.ts
  libs/zephyr-agent/src/lib/auth/auth-flags.ts
  libs/zephyr-agent/src/lib/auth/login.test.ts
  libs/zephyr-agent/src/lib/auth/login.ts
  libs/zephyr-agent/src/lib/auth/websocket.ts
Labels: QA: Approved

#60 fix: proceed with login without requiring enter keypress
  libs/zephyr-agent/src/lib/auth/login.ts
  libs/zephyr-agent/src/lib/logging/ze-log-event.ts
Labels: QA: Approved

#59 feat: to switch to *.ze
  libs/zephyr-agent/src/lib/node-persist/upload-provider-options.ts
  libs/zephyr-agent/src/lib/transformers/ze-build-dash-data.ts
  libs/zephyr-edge-contract/src/lib/zephyr-build-stats.ts
  libs/zephyr-xpack-internal/src/federation-dashboard-legacy/get-build-stats.ts
  libs/zephyr-xpack-internal/src/xpack-extract/ze-xpack-upload-agent.ts
Labels: QA: Approved

#65 feat: ensure repack plugin work with repack ^v5.0.0
  libs/zephyr-agent/src/index.ts
  libs/zephyr-agent/src/lib/errors/codes.ts
  libs/zephyr-agent/src/zephyr-engine/index.ts
  libs/zephyr-repack-plugin/package.json
  libs/zephyr-repack-plugin/src/delegate-module/delegate-module-template.ts
  libs/zephyr-repack-plugin/src/lib/utils/get-platform.ts
  libs/zephyr-repack-plugin/src/lib/with-zephyr.ts
  libs/zephyr-repack-plugin/src/lib/ze-repack-plugin.ts
  libs/zephyr-repack-plugin/src/type/zephyr-internal-types.ts
  libs/zephyr-xpack-internal/src/hooks/ze-setup-ze-deploy.ts
  libs/zephyr-xpack-internal/src/xpack-extract/create-mf-runtime-code.ts
  libs/zephyr-xpack-internal/src/xpack-extract/mut-webpack-federated-remotes-config.ts
  libs/zephyr-xpack-internal/src/xpack.types.ts
  pnpm-lock.yaml
Labels: Ready for testing

#67 fix: remove awaiting for hash list request
  libs/zephyr-agent/package.json
  libs/zephyr-agent/src/zephyr-engine/index.ts
  pnpm-lock.yaml
Labels: enhancement
